author: Kaltura
author_url: "http://corp.kaltura.com"
github_url: "https://github.com/kaltura/playkit-ios"
# github_file_prefix used for showing "Show in Github" links, must be same repo used for the docs generation.
github_file_prefix: "https://github.com/kaltura/playkit-ios/tree/master" 
copyright: "Copyright © 2016 Kaltura Inc. All Rights Reserved."
clean: true

exclude: [Example/]
xcodebuild_arguments: [-workspace, "PlayKitFramework/PlayKitFramework.xcworkspace", -scheme, PlayKitFramework]
output: jazzy/docs/

theme: fullwidth

custom_categories:
  - name: Player
    children:
    - Player
    - PlayerDelegate
    - PlayerConfig
    - PlayerDecoratorBase
    - PlayerState
    - MediaEntry
    - Track
    - PKTracks

  - name: Network
    children:
    - Request
    - RequestElement
    - RequestBuilder
    - RequestConfiguration
    - RequestExecutor

  - name: Events
    children:
    - MessageBus
    - PlayerEvents 
    - AdEvents
    - PKEvent
    