language: objective-c
osx_image: xcode8.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install jazzy
script:
  - cd PlayKitFramework
  - pod install
  - echo Starting build...
  - xcodebuild -scheme PlayKitFramework -workspace PlayKitFramework.xcworkspace
  - cd .. # go up one folder back to root
  - echo Starting jazzy, soulful docs for Swift and Objective-C...
  - jazzy # apple docs generator tool
  - ./scripts/gh-pages-deploy-ios.sh # apple docs deploy script
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - eliza.sapir@kaltura.com
      - gal.orlanczyk@kaltura.com
    on_success: change
    on_failure: always
