language: objective-c
osx_image: xcode8.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install jazzy
script:
  - cd PlayKitFramework
  - pod install
  - cd .. # go up one folder back to root
  - ./scripts/gh-pages-deploy-ios.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - eliza.sapir@kaltura.com
      - gal.orlanczyk@kaltura.com
    on_success: change
    on_failure: always
