language: objective-c
osx_image: xcode8.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install jazzy
script:
  - cd PlayKitFramework
  - pod install
  # build command is being run inside .jazzy.script
  # - xcodebuild -scheme PlayKitFramework -workspace PlayKitFramework.xcworkspace
  - jazzy
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - eliza.sapir@kaltura.com
    on_success: change
    on_failure: always
